resource.AddFile("materials/gmod/scope.vmt")
resource.AddFile("materials/gmod/scope-refract.vmt")
resource.AddFile("materials/gmod/scope.vtf")
resource.AddFile("materials/gmod/scope-refract.vtf")
resource.AddFile("materials/gmod/scope-refract.vtf.vtmp")
resource.AddFile("materials/gmod/scope.vtf.vtmp")